version: "3"
services:
  sphinx:
    image: "nickjer/docker-sphinx"
    volumes:
      - ".:/doc"
    ports:
      - "2999:2999"
    command: sphinx-autobuild -b html -p 2999 -H 0.0.0.0 --ignore *.swp source build
